name: spritewidget_flint_particles
description: Flint particle system for SpriteWidget/EspritWidget.
version: 0.0.1
author: Richard Lord (AS3), Dan Syrstad (Dart/Flutter)
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  spritewidget:
    path: ../spritewidget

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
