name: demo
description: A demo of the SpriteWidget Flint particle system.

version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  spritewidget_flint_particles:
    path: ../..
  spritewidget:
    path: ../../../spritewidget

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
